### PR TITLE
Icon support for SettingButton and SettingPicker and trailing label support for SettingPage

### PR DESCRIPTION
**Pull request by Saik0s**
Thanks for creating an awesome library! 

This PR implements icon support for SettingButton and SettingPicker, as well as trailing label support for SettingPage, to ensure consistency with the look and feel of iOS Settings.

### CODE REVIEW

**Comment by Saik0s** [comment]
This PR would cover https://github.com/aheze/Setting/issues/12

**Comment by aheze** [comment]
Thanks for the PR - sorry for getting back to you so late. Checking this out...

**Comment by aheze** [comment]
Thanks!

**Comment by aheze** [comment]
Resolved the merge conflict here: https://github.com/aheze/Setting/commit/4f9c736e119b91ebbf1b06426588f7f6e81cc54e

**Comment by aheze** [comment]
Added an example:

Buttons with icon on the left

```swift
SettingPage(title: "Extras", selectedChoice: "Hello, world!") {
    SettingGroup {
        SettingButton(title: "Hello, world!") {
            print("Hello world pressed!")
        }
        .icon(icon: .system(icon: "ellipsis", backgroundColor: Color.teal))
    }
    
    SettingGroup {
        SettingButton(title: ":)") {
            print(":) pressed!")
        }
        .icon(icon: .system(icon: "sparkles", backgroundColor: Color.pink))
        .indicator("face.smiling")
    }
}
.previewIcon(icon: .system(icon: "ellipsis", backgroundColor: Color.teal))
```

**Pull request merged**
